= The `valid8j` library powered by `pcond`

`valid8j` (pronounced validate-j) is a DbC (design by contract<<DbC>>) library named after `valid4j`<<valid4j>>.
It uses `pcond`<<pcond>>, which provides you with predicates that can print descriptive message on a failure, instead of `hamcrest` used by `valid4j`.
The benefit of `pcond` over `hamcrest` is its compatibility and extensibility.
Instead of "matchers" that `hamcrest` uses to verify values, `pcond` uses Java's plain `Predicate` and provide useful preset predicates from which you can build your own predicates for complex types.
So, you can reuse the predicates you created for assertions for other purposes, such as value checking and testing.

A design idea behind `pcond` is following:
When a human checks test results, he/she wants to "see" the values on a display screen as texts.
But what sort of values they can check?
Numbers, texts, boolean, null, or compound values of them.
Database records, HTTP requests, responses, List, Map, ... they can be decomposed into the handful of value types.
If cannot, they cannot be understood by human, either way.
If so, when a human checks such a complex value, what human does will be to extract a certain aspect of the original complex value as a simple value and check if it satisfies a certain predicate for a simple value type.
If so, the mechanism we desire for a versatile assertion library is not to be able to build a matcher for any types, but to be able to define a function to "transform"  a given object to a simple value, and provide a useful and preset predicates sufficient for checking the extracted value.

This allows you to use the library for your custom class very easily.

Not only that, it allows "no-overhead" execution of assertions, which gives no performance penalty at production code, yet keeping its descriptiveness on failures.

== Before Using: `assert var != null` vs `Objects.requireNonNull(var)`

What are the differences between them?
For what a situation do you use `assert` or `requireNonNull`?

`assert` throws `java.lang.AssertionError` and for `requireNonNull`, `java.lang.NullPointerException` is thrown, when the `var` is `null`.
And, in both cases, we consider that a bug is detected and therefore, the exception should not be caught.

Then which should be used when?

[ditaa]
----
+------+    +-----------------------+
|Client|    |Your Product           |
|      |    |    +----------------+ |
|      +--->|    |Internal Classes| |
|      |    |    +----------------+ |
+------+    +-----------------------+
----

The author of `valid8j` thinks as follows:

- When you are detecting a bug of your client's, use `requireNonNull(var)`: Because you want to enforce a certain constraint on the values your user client gives to your product.
- When you are detecting a bug of your own library, use `assert var != null`: Because you want to allow your users to disable the checks to provide the best performance of your product.

If so, as a rule of thumb, the former should be used in `public`  in general, and the other, in `private` or package-private methods.

=== One More Consideration

In public methods, we throw `NullPointerException` and `IllegalArgumentException` if a given argument doesn't satisfy a constraint a method has.
This is widely accepted convention, but does it hold anytime?
Perhaps, your product may have a policy about exceptions to be thrown, where custom exceptions should always be used to be able to compose a user-friendly message.

You can tweak exceptions to be thrown by "reconfigure" a `Validator` instance used in your current thread.
Check `Validator.reconfigure` and `Validator.Configuration.Builder.exceptionComposerForRequire` to configure the exceptions to be thrown when a requirement for your method is broken.

== Usage
First, let's import statically entry points of the library in your code.

[source,java]
----
import static com.github.dakusui.valid8j.Assertions.precondition;
import static com.github.dakusui.valid8j.Requires.require;
----

Of course, you can rely on your IDE for it, though.

[source,java]
----
import static com.github.dakusui.valid8j_pcond.forms.Functions.length;
import static com.github.dakusui.valid8j_pcond.forms.Predicates.*;
public class Example {
  public void publicMethod(String message) {
    require(message, and(isNotNull(), transform(length()).check(greaterThan(0))));
    privateMethod(message);
  }

  private void privateMethod(String message) {
    assert precondition(message, and(isNotNull(), transform(length()).check(greaterThan(0))));
    System.out.println(message);
  }
}
----

If you give `null` to the methods in the example, you will get a following output.

----
Exception in thread "main" com.github.dakusui.valid8j_pcond.validator.exceptions.PreconditionViolationException: value:<null> violated precondition:value (isNotNull&&length >[0])
Mismatch<:    null->and         ->true
Mismatch>:    null->and         ->false
Mismatch<:[0]     ->  isNotNull ->true
Mismatch>:[0]     ->  isNotNull ->false

.Detail of failure [0] (expectation)
---
isNotNull
---

.Detail of failure [0] (actual value)
---
null
---
	at com.github.dakusui.valid8j_pcond.validator.ExceptionComposer$ForRequire.exceptionForGeneralViolation(ExceptionComposer.java:164)
	at com.github.dakusui.valid8j_pcond.validator.Validator.lambda$require$1(Validator.java:101)----
----

Note that the `that` method throws an exception rather than returning `false` when the given predicate results in `false` and therefore it can compose the descriptive exception message.

== Performance

The `precondition` method is defined to return a `boolean` value.

[source,java]
----
public class Example {
  private void privateMethod(String message) {
    assert precondition(message, isNotNull()); //<1>
    System.out.println(mesage);
  }
}
----
<1> This line is not executed at all if you give `-da` option to your JVM.

But it will never return `false`.
If the method finds the predicate results in `false`, it will throw an exception, instead of returning `false`.
In the exception, an informative message will be embedded.

From the performance perspective, the `precondition` method is relatively time-consuming because it traverses the predicate tree to compose a message.
However, here's one thing, it's an expression passed to `assert` statement.
If you disable assertion (`-da`), which is the practice you always exercise in the production code, the statement will not be executed at all.
So, there will be no performance overhead in production.
Also, note that you can even control the assertion behavior per-package basis<<assertions>>.
This is why you should prefer `valid8j` over existing value checking libraries such as `Preconditions`<<Preconditions-guava>> or `Validates`<<Validates-apache-commons>>.

[bibliography]
== References

- [[[DbC, 1]]] Wikipedia article on Design by Contract, https://en.wikipedia.org/wiki/Design_by_contract
- [[[valid4j, 2]]] valid4j https://www.valid4j.org/[valid4j.org
- [[[pcond, 3]]] pcond https://dakusui.github.io/pcond/[github.com/pcond]
- [[[assertions, 4]]] Programming With Assertions https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html
- [[[Preconditions-guava, 5]]] Preconditions, Google Guava https://guava.dev/releases/19.0/api/docs/com/google/common/base/Preconditions.html[Preconditions class]
- [[[Validates-apache-commons, 6]]] Validates, Apache Commons https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/Validate.html[Validate class]
